
  spring:
    config:
      import: "optional:configserver:http://localhost:1018"
  application:
    name: department-service


  management:
    tracing:
      sampling:
        probability: 1.0



