server:
  port: 8060

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/department/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/

management:
  tracing:
    sampling:
      probability: 1.0



